Add an on_exit flag
stereolabs/zed-ros2-wrapper pull request #121
Opened 2022-11-25 09:35 UTC by maxpolzin

Adding the on_exit flag shuts down all launched nodes if one of the nodes crashes. This is particularly useful when running the ZED wrapper in Docker containers where the docker conatiner is supposed to restart if one node dies.

2022-11-25 11:03 UTC, Myzhar requested changes
I'm sorry, but those settings cannot be added as the default configuration

2022-11-25 12:32 UTC, maxpolzin commented
For sure not problem, the MR was more to raise awareness of the function. :)

2022-11-25 12:45 UTC, Myzhar commented
The event handler is indeed a good idea.
I was referring to depth mode and resolution parameters

2022-11-26 17:53 UTC, Myzhar requested changes
A grab frame rate of 20 Hz cannot be used.
The camera HW allows 4 fixed values:
15, 30, 60, 100.
100 is available only for VGA
60 is available for VGA and 720p
30 is available for VGA, 720p and 1080p
15 can be used with all the resolutions.

Publish framerate can be instead set to every value minor or equal to grab frame rate because it sets the frequency of the publishing thread.

2023-11-28 15:44 UTC, closed without merging